import { existsSync, readFileSync, readdirSync } from 'node:fs'
import { join, resolve } from 'node:path'
import { describe, expect, it } from 'vitest'
import { normalizePath } from './normalize-path'

/**
 * The gate on the legacy WordPress redirect map.
 *
 * `data/legacy/redirect-map.json` is generated by
 * `scripts/build-legacy-redirects.mjs`, which talks to production. This file
 * re-checks the artefact with NO network and no database, so it runs in CI and
 * on a laptop with a dead key, and it fails on every defect class that was
 * actually found in the map the database would have projected on 2026-09-09:
 *
 *   1. `/blog` was marked 410 while `/blog` is a live route in this app. The
 *      proxy answers 410 before routing, so the row would have taken an
 *      indexed, working page off the internet.
 *   2. Eleven category rows pointed at Hebrew slugs. Production categories
 *      carry English ones, so every row was a 301 into a 404.
 *   3. Two `/product/...₪` rows redirected one LIVE product at another. Both
 *      are active; they are the duplicate pair CLAUDE.md blocker #1 records,
 *      and which one is real is the operator's call, not a 301's.
 *
 * Every one of those is silent. Nothing throws, nothing logs, the row count
 * looks right, and the only symptom is traffic that quietly stops arriving.
 */

const ROOT = resolve(__dirname, '../../..')
const MAP_PATH = join(ROOT, 'data/legacy/redirect-map.json')
const SQL_PATH = join(ROOT, 'migrations/pending/192_seed_seo_redirects.sql')

type Redirect = {
  source: string
  target: string
  status: 301 | 410
  rule: string
  entity: string
  wp_id: number | null
}

type RedirectMap = {
  $counts: { inventory: number; redirects: number; redirect_301: number; redirect_410: number }
  $sitemap_diff: {
    legacy_urls: number
    served_unchanged: number
    redirected_301: number
    gone_410: number
    lost_404: number
    lost: string[]
  }
  $targets: {
    products: string[]
    categories: { slug: string; name_he: string }[]
    static_routes: string[]
  }
  redirects: Redirect[]
  excluded: { source: string; reason: string; note: string }[]
}

const map: RedirectMap = JSON.parse(readFileSync(MAP_PATH, 'utf8'))
const sql = readFileSync(SQL_PATH, 'utf8')

/** Independently re-derived, so this file can disagree with the generator. */
function staticRoutesFromDisk(dir = join(ROOT, 'src/app'), prefix = ''): string[] {
  const out: string[] = []
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    if (!entry.isDirectory()) continue
    const name = entry.name
    if (name.startsWith('_') || name.startsWith('@') || name.startsWith('[')) continue
    // `/dev/**` is not something this site serves. Those pages call
    // `notFound()` under NODE_ENV=production, so counting them as live routes
    // would tell the redirect builder that a path exists which every real
    // visitor gets a 404 for.
    if (prefix === '' && name === 'dev') continue
    const segment = name.startsWith('(') && name.endsWith(')') ? '' : `/${name}`
    const child = join(dir, name)
    if (existsSync(join(child, 'page.tsx')) || existsSync(join(child, 'page.ts'))) {
      out.push(normalizePath(prefix + segment))
    }
    out.push(...staticRoutesFromDisk(child, prefix + segment))
  }
  if (prefix === '' && existsSync(join(dir, 'page.tsx'))) out.push('/')
  return [...new Set(out)].sort()
}

const routes = new Set(map.$targets.static_routes)
const products = new Set(map.$targets.products)
const categories = new Set(map.$targets.categories.map((c) => c.slug))
const sources = new Set(map.redirects.map((r) => r.source))

/** What a request for this path gets today, or null if nothing serves it. */
function servedBy(path: string): string | null {
  if (routes.has(path)) return 'static route'
  if (path.startsWith('/product/') && products.has(path.slice('/product/'.length))) return 'product'
  if (path.startsWith('/category/') && categories.has(path.slice('/category/'.length))) {
    return 'category'
  }
  return null
}

describe('the artefact describes this repository', () => {
  it('lists exactly the static routes src/app defines', () => {
    // The one assertion that makes every other check in this file trustworthy.
    // Without it a route added after the last rebuild is invisible here, which
    // is precisely how /blog came to be marked gone: the page was added after
    // the 2026-08-11 crawl and nothing re-asked the question.
    expect(map.$targets.static_routes).toEqual(staticRoutesFromDisk())
  })

  it('puts every legacy URL in exactly one bucket', () => {
    // What makes the map an ANSWER and not a sample. A legacy URL that reaches
    // neither list is one nobody decided about, and the symptom of a URL nobody
    // decided about is a 404 that raises nothing.
    const inventory = JSON.parse(
      readFileSync(join(ROOT, 'data/legacy/url-inventory.json'), 'utf8'),
    ) as { rows: { old_path: string }[] }

    const decided = [...map.redirects.map((r) => r.source), ...map.excluded.map((e) => e.source)]
    expect(new Set(decided).size).toBe(decided.length)
    expect(decided.sort()).toEqual(inventory.rows.map((r) => normalizePath(r.old_path)).sort())

    const d = map.$sitemap_diff
    expect(d.served_unchanged + d.redirected_301 + d.gone_410 + d.lost_404).toBe(d.legacy_urls)
    expect(d.legacy_urls).toBe(inventory.rows.length)
  })

  it('names the legacy URLs that still 404, rather than only counting them', () => {
    // Three product URLs the old site served have no destination on this one:
    // `restaurants-meat-2` and `restaurants-meat-3` exist as DRAFT rows and
    // `קופון-טסט` does not exist at all (measured against production,
    // 2026-09-09). None of the three gets a redirect and the reason differs
    // per row -- a draft can be published, and a 410 would make that
    // publication unreachable -- so they are named here instead. A fourth
    // appearing is a change worth seeing.
    expect(map.$sitemap_diff.lost).toEqual([
      '/product/restaurants-meat-2',
      '/product/restaurants-meat-3',
      '/product/קופון-טסט',
    ])
  })

  it('carries the counts it claims', () => {
    expect(map.redirects).toHaveLength(map.$counts.redirects)
    expect(map.redirects.filter((r) => r.status === 301)).toHaveLength(map.$counts.redirect_301)
    expect(map.redirects.filter((r) => r.status === 410)).toHaveLength(map.$counts.redirect_410)
  })
})

describe('no redirect shadows a page that works', () => {
  it('never takes a live path as a source', () => {
    // A 301 on a live path hides it; a 410 on a live path removes it from the
    // index with the one status code that tells a crawler not to come back.
    const shadowed = map.redirects
      .map((r) => ({ ...r, live: servedBy(r.source) }))
      .filter((r) => r.live !== null)
      .map((r) => `${r.status} ${r.source} shadows a live ${r.live}`)

    expect(shadowed).toEqual([])
  })

  it('keeps the pages that proved the rule out of the map', () => {
    // Named, not just counted. These three are the measured findings; if a
    // future rebuild lets any of them back in, the count assertion above would
    // still pass and this one would not.
    for (const path of [
      '/blog',
      '/product/עיסוי-מפנק-לגבר-45-דקות-רק-ב108₪',
      '/product/עיסוי-משולב-מפנק-לגבר-רק-108₪',
    ]) {
      expect(sources.has(path)).toBe(false)
      expect(map.excluded.find((e) => e.source === path)?.reason).toBe('source_is_live')
    }
  })
})

describe('no redirect points at a page that does not exist', () => {
  it('sends every 301 somewhere this site serves', () => {
    // A 301 into a 404 is worse than the 404 it replaces: Search Console files
    // it under "redirect", so the broken destination never surfaces as a
    // broken page and the loss is invisible.
    const broken = map.redirects
      .filter((r) => r.status === 301 && servedBy(r.target) === null)
      .map((r) => `${r.source} -> ${r.target} (nothing serves the target)`)

    expect(broken).toEqual([])
  })

  it('resolves every legacy category to a live English slug', () => {
    // The Hebrew slugs the old site used exist nowhere in this database. All
    // eleven of them had to be re-resolved by name, and four by hand.
    const legacy = map.redirects.filter((r) => r.source.startsWith('/product-category/'))
    expect(legacy).toHaveLength(11)
    for (const row of legacy) {
      expect(row.target).not.toMatch(/[֐-׿]/)
      expect(servedBy(row.target)).not.toBeNull()
    }
  })
})

describe('the map is well formed', () => {
  it('stores every source in the form the proxy looks up', () => {
    // The proxy calls normalizePath() on the incoming pathname and then does
    // one Map.get(). A source stored in any other form -- percent-encoded,
    // trailing-slashed, NFD Hebrew -- is a row no request can ever match, and
    // the failure looks exactly like a redirect that was never configured.
    // Running it through the TYPESCRIPT normalizer is the point: the generator
    // has its own copy, and this is where the two are made to agree.
    for (const row of map.redirects) expect(normalizePath(row.source)).toBe(row.source)
  })

  it('has no duplicate source', () => {
    expect(sources.size).toBe(map.redirects.length)
  })

  it('never chains one redirect into another', () => {
    // Two hops cost a round trip and Google follows a limited number of them.
    const chained = map.redirects.filter((r) => r.status === 301 && sources.has(r.target))
    expect(chained).toEqual([])
  })

  it('gives a 301 a destination and a 410 none', () => {
    for (const row of map.redirects) {
      if (row.status === 410) expect(row.target).toBe('')
      else expect(row.target.startsWith('/')).toBe(true)
    }
  })
})

describe('the seed migration matches the map', () => {
  it('carries one row per redirect and no others', () => {
    // The SQL and the JSON come out of the same run, so they can only drift by
    // a hand edit -- which is exactly the edit that would not be reviewed.
    for (const row of map.redirects) {
      const escaped = row.source.replace(/'/g, "''")
      expect(sql, `missing ${row.source}`).toContain(
        `('${escaped}', '${row.target}', ${row.status}`,
      )
    }
    // Counted off the VALUES tuples themselves, not off every indented paren:
    // the second INSERT opens with its own indented column list and would
    // otherwise be read as a thirty-fourth row.
    const values = sql.slice(sql.indexOf('INSERT INTO _seed'), sql.indexOf('INSERT INTO public.'))
    expect(values.match(/^ {2}\('/gm) ?? []).toHaveLength(map.redirects.length)
  })

  it('asserts its own row count before committing', () => {
    expect(sql).toContain(`IF n <> ${map.redirects.length} THEN`)
  })
})
