/**
 * iOS launch images. Safari ignores the manifest's `background_color` and
 * shows a white screen on launch unless a `apple-touch-startup-image` matches
 * the device exactly, so each screen is one PNG at the device's pixel size
 * with a media query on its CSS size and pixel ratio. Generated by
 * `scripts/generate-pwa-splash.mjs`; `splash.test.ts` checks every file is
 * there at the declared size.
 *
 * Portrait only: the manifest says `orientation: portrait` and the shop has no
 * landscape layout worth a launch image.
 */

export interface SplashScreen {
  /** CSS points. */
  width: number
  height: number
  ratio: 2 | 3
  /** Which phones this covers, for the reader. */
  devices: string
}

export const SPLASH_SCREENS: readonly SplashScreen[] = [
  { width: 375, height: 667, ratio: 2, devices: 'iPhone SE (2nd/3rd), 8' },
  { width: 375, height: 812, ratio: 3, devices: 'iPhone X/XS/11 Pro, 12/13 mini' },
  { width: 390, height: 844, ratio: 3, devices: 'iPhone 12/13/14, 12/13 Pro' },
  { width: 393, height: 852, ratio: 3, devices: 'iPhone 14 Pro, 15, 15 Pro, 16' },
  { width: 402, height: 874, ratio: 3, devices: 'iPhone 16 Pro' },
  { width: 414, height: 896, ratio: 2, devices: 'iPhone XR, 11' },
  { width: 414, height: 896, ratio: 3, devices: 'iPhone XS Max, 11 Pro Max' },
  { width: 428, height: 926, ratio: 3, devices: 'iPhone 12/13 Pro Max, 14 Plus' },
  { width: 430, height: 932, ratio: 3, devices: 'iPhone 14 Pro Max, 15 Plus/Pro Max, 16 Plus' },
  { width: 440, height: 956, ratio: 3, devices: 'iPhone 16 Pro Max' },
]

export function splashFileName(screen: SplashScreen): string {
  return `splash-${screen.width * screen.ratio}x${screen.height * screen.ratio}.png`
}

export function splashMedia(screen: SplashScreen): string {
  return `screen and (device-width: ${screen.width}px) and (device-height: ${screen.height}px) and (-webkit-device-pixel-ratio: ${screen.ratio}) and (orientation: portrait)`
}

/** For `metadata.appleWebApp.startupImage`. */
export function startupImages(): { url: string; media: string }[] {
  return SPLASH_SCREENS.map((screen) => ({
    url: `/splash/${splashFileName(screen)}`,
    media: splashMedia(screen),
  }))
}
