/**
 * The hosted project's columns for every table the payment finalize path
 * touches, read from `information_schema.columns` on 2026-10-08 (STEP 40),
 * plus the identity arguments of the five functions it calls, from
 * `pg_proc`. Hard-coded on purpose, in the spirit of the 2026-07-31 lists in
 * order-money-columns.test.ts: the test that matters is "every column this
 * code names exists in the database it runs against, and nothing it WRITES is
 * GENERATED", and that cannot be asserted against a schema nobody wrote down.
 * `src/types/database.ts` is not that schema: it was generated before 224 and
 * knows neither `orders.cashback_applied_agorot` nor
 * `order_items.unit_price_agorot`, which is why finalize casts its rows.
 *
 * `generated` is `is_generated = 'ALWAYS'`: readable under the post-059 name,
 * but an INSERT or UPDATE that names one fails with 428C9 - the exact landmine
 * 224 was written to defuse on the read side. `required` is NOT NULL with no
 * default: omitting one from an insert fails as surely as naming a column that
 * is missing.
 *
 * Refresh (read-only, management API with the CLI token, see
 * docs/RUNBOOK.md): re-run the two queries below and replace the literals in
 * the same commit as the code that needs the new column.
 *
 *   select table_name, column_name, is_nullable, column_default, is_generated
 *   from information_schema.columns
 *   where table_schema = 'public' and table_name in (<the tables below>)
 *   order by 1, 2;
 *
 *   select proname, pg_get_function_identity_arguments(oid)
 *   from pg_proc where pronamespace = 'public'::regnamespace
 *   and proname in (<the functions below>);
 */

export type HostedColumn = { generated: boolean; required: boolean }

export const HOSTED_SCHEMA_MEASURED_ON = '2026-10-08'

export const HOSTED_COLUMNS: Record<string, Record<string, HostedColumn>> = {
  audit_log: {
    action: { generated: false, required: true },
    actor_id: { generated: false, required: false },
    actor_role: { generated: false, required: false },
    after: { generated: false, required: false },
    before: { generated: false, required: false },
    changes: { generated: false, required: false },
    created_at: { generated: false, required: false },
    entity_id: { generated: false, required: true },
    entity_type: { generated: false, required: true },
    id: { generated: false, required: false },
    ip_address: { generated: false, required: false },
    metadata: { generated: false, required: false },
    request_id: { generated: false, required: false },
    user_agent: { generated: false, required: false },
  },
  carts: {
    created_at: { generated: false, required: false },
    expires_at: { generated: false, required: false },
    id: { generated: false, required: false },
    items: { generated: false, required: false },
    profile_id: { generated: false, required: false },
    session_id: { generated: false, required: false },
    updated_at: { generated: false, required: false },
  },
  order_items: {
    balance_due_agorot: { generated: false, required: false },
    carrier: { generated: false, required: false },
    cashback_amount_agorot: { generated: false, required: false },
    cashback_earned_ils: { generated: false, required: false },
    cashback_earned_ils_agorot: { generated: true, required: false },
    cashback_percent: { generated: false, required: false },
    commission_agorot: { generated: false, required: false },
    commission_percent: { generated: false, required: true },
    commission_percent_snapshot: { generated: false, required: false },
    coupon_price_ils: { generated: false, required: false },
    coupon_price_ils_agorot: { generated: true, required: false },
    created_at: { generated: false, required: false },
    deleted_at: { generated: false, required: false },
    delivered_at: { generated: false, required: false },
    discount_percent: { generated: false, required: false },
    escrow_held_agorot: { generated: false, required: false },
    escrow_release_agorot: { generated: false, required: false },
    face_value_agorot: { generated: false, required: false },
    fulfilled_at: { generated: false, required: false },
    id: { generated: false, required: false },
    item_status: { generated: false, required: false },
    order_id: { generated: false, required: true },
    paid_on_site_agorot: { generated: false, required: false },
    platform_percent: { generated: false, required: false },
    product_id: { generated: false, required: false },
    product_type: { generated: false, required: true },
    quantity: { generated: false, required: false },
    settlement_status: { generated: false, required: false },
    shipped_at: { generated: false, required: false },
    supplier_address: { generated: false, required: false },
    supplier_id: { generated: false, required: false },
    supplier_immediate_agorot: { generated: false, required: false },
    supplier_logo_url: { generated: false, required: false },
    supplier_name: { generated: false, required: false },
    supplier_payout_ils: { generated: false, required: true },
    supplier_payout_ils_agorot: { generated: true, required: false },
    supplier_phone: { generated: false, required: false },
    supplier_split_percent: { generated: false, required: false },
    total_price_ils: { generated: false, required: true },
    total_price_ils_agorot: { generated: true, required: false },
    tracking_number: { generated: false, required: false },
    unit_price_agorot: { generated: true, required: false },
    unit_price_ils: { generated: false, required: true },
    unit_price_ils_agorot: { generated: true, required: false },
    updated_at: { generated: false, required: false },
    upfront_percent: { generated: false, required: false },
    variant_id: { generated: false, required: false },
  },
  orders: {
    accepted_terms_at: { generated: false, required: false },
    address_id: { generated: false, required: false },
    affiliate_code: { generated: false, required: false },
    cardcom_payment_id: { generated: false, required: false },
    cashback_applied_agorot: { generated: true, required: false },
    cashback_applied_ils: { generated: false, required: false },
    cashback_applied_ils_agorot: { generated: true, required: false },
    created_at: { generated: false, required: false },
    currency: { generated: false, required: false },
    deleted_at: { generated: false, required: false },
    discount_ils: { generated: false, required: false },
    discount_ils_agorot: { generated: true, required: false },
    expires_at: { generated: false, required: false },
    gift_message: { generated: false, required: false },
    gift_recipient_email: { generated: false, required: false },
    gift_recipient_name: { generated: false, required: false },
    id: { generated: false, required: false },
    invoice_number: { generated: false, required: false },
    notes: { generated: false, required: false },
    paid_at: { generated: false, required: false },
    referral_code_used: { generated: false, required: false },
    status: { generated: false, required: false },
    subtotal_ils: { generated: false, required: true },
    subtotal_ils_agorot: { generated: true, required: false },
    total_ils: { generated: false, required: true },
    total_ils_agorot: { generated: true, required: false },
    updated_at: { generated: false, required: false },
    user_id: { generated: false, required: true },
  },
  payment_tokens: {
    card_brand: { generated: false, required: false },
    cardcom_account_id: { generated: false, required: false },
    cardcom_token: { generated: false, required: true },
    created_at: { generated: false, required: false },
    expiry_month: { generated: false, required: false },
    expiry_year: { generated: false, required: false },
    id: { generated: false, required: false },
    is_default: { generated: false, required: false },
    last_4: { generated: false, required: false },
    profile_id: { generated: false, required: true },
  },
  payments: {
    amount_ils: { generated: false, required: true },
    amount_ils_agorot: { generated: true, required: false },
    cardcom_account_id: { generated: false, required: false },
    cardcom_low_profile_id: { generated: false, required: false },
    cardcom_transaction_id: { generated: false, required: false },
    created_at: { generated: false, required: false },
    currency: { generated: false, required: false },
    failed_at: { generated: false, required: false },
    failure_code: { generated: false, required: false },
    failure_message: { generated: false, required: false },
    id: { generated: false, required: false },
    idempotency_key: { generated: false, required: false },
    kind: { generated: false, required: false },
    order_id: { generated: false, required: true },
    raw_response: { generated: false, required: false },
    refund_of_payment_id: { generated: false, required: false },
    status: { generated: false, required: false },
    succeeded_at: { generated: false, required: false },
    updated_at: { generated: false, required: false },
    wallet_applied_ils: { generated: false, required: false },
  },
  products: {
    approval_note: { generated: false, required: false },
    approval_status: { generated: false, required: false },
    approved_at: { generated: false, required: false },
    approved_by: { generated: false, required: false },
    attributes: { generated: false, required: false },
    barcode: { generated: false, required: false },
    billing_interval: { generated: false, required: false },
    billing_interval_count: { generated: false, required: false },
    brand: { generated: false, required: false },
    cashback_enabled: { generated: false, required: false },
    cashback_percent: { generated: false, required: false },
    category_id: { generated: false, required: false },
    city: { generated: false, required: false },
    commission_percent: { generated: false, required: true },
    commission_type: { generated: false, required: true },
    compare_at_price: { generated: false, required: false },
    compare_at_price_agorot: { generated: true, required: false },
    compare_at_price_ils: { generated: false, required: false },
    compare_at_price_ils_agorot: { generated: true, required: false },
    condition: { generated: false, required: false },
    cost_ils: { generated: false, required: false },
    coupon_expiry_days: { generated: false, required: false },
    coupon_price_ils: { generated: false, required: false },
    coupon_price_ils_agorot: { generated: true, required: false },
    coupon_terms_he: { generated: false, required: false },
    created_at: { generated: false, required: false },
    created_by: { generated: false, required: false },
    deleted_at: { generated: false, required: false },
    description_he: { generated: false, required: false },
    discount_percent: { generated: false, required: false },
    full_price: { generated: false, required: false },
    full_price_agorot: { generated: true, required: false },
    height_cm: { generated: false, required: false },
    height_mm: { generated: false, required: false },
    highlights: { generated: false, required: false },
    id: { generated: false, required: false },
    images: { generated: false, required: false },
    is_coupon_enabled: { generated: false, required: false },
    is_featured: { generated: false, required: false },
    is_gift_card: { generated: false, required: false },
    kenyon_price: { generated: false, required: false },
    kenyon_price_agorot: { generated: true, required: false },
    latitude: { generated: false, required: false },
    length_cm: { generated: false, required: false },
    length_mm: { generated: false, required: false },
    longitude: { generated: false, required: false },
    low_stock_threshold: { generated: false, required: false },
    max_per_order: { generated: false, required: false },
    min_purchase_ils: { generated: false, required: false },
    name_en: { generated: false, required: false },
    name_he: { generated: false, required: true },
    offer_valid_until: { generated: false, required: false },
    platform_percent: { generated: false, required: false },
    price_ils: { generated: false, required: true },
    price_ils_agorot: { generated: true, required: false },
    profit_share_cap_percent: { generated: false, required: false },
    published_at: { generated: false, required: false },
    recurring_amount_agorot: { generated: false, required: false },
    redemption_instructions_he: { generated: false, required: false },
    requires_shipping: { generated: false, required: false },
    search_vector: { generated: true, required: false },
    seo_description: { generated: false, required: false },
    seo_keywords: { generated: false, required: false },
    seo_title: { generated: false, required: false },
    short_description_he: { generated: false, required: false },
    sku: { generated: false, required: false },
    slug: { generated: false, required: true },
    status: { generated: false, required: false },
    stock_initial: { generated: false, required: false },
    stock_quantity: { generated: false, required: false },
    submitted_at: { generated: false, required: false },
    supplier_id: { generated: false, required: false },
    supplier_split_percent: { generated: false, required: false },
    tags: { generated: false, required: false },
    type: { generated: false, required: true },
    updated_at: { generated: false, required: false },
    vat_exempt: { generated: false, required: false },
    video_url: { generated: false, required: false },
    warranty_months: { generated: false, required: false },
    weight_grams: { generated: false, required: false },
    whatsapp_enabled: { generated: false, required: false },
    width_cm: { generated: false, required: false },
    width_mm: { generated: false, required: false },
  },
  profiles: {
    affiliate_code: { generated: false, required: false },
    avatar_url: { generated: false, required: false },
    created_at: { generated: false, required: false },
    email: { generated: false, required: true },
    full_name: { generated: false, required: false },
    id: { generated: false, required: true },
    phone: { generated: false, required: false },
    referral_code: { generated: false, required: false },
    role: { generated: false, required: false },
    total_purchases: { generated: false, required: false },
    updated_at: { generated: false, required: false },
    wallet_balance: { generated: false, required: false },
    wallet_balance_agorot: { generated: true, required: false },
  },
  split_executions: {
    commission_agorot: { generated: false, required: true },
    created_at: { generated: false, required: false },
    executed_at: { generated: false, required: false },
    face_value_agorot: { generated: false, required: true },
    id: { generated: false, required: false },
    order_id: { generated: false, required: true },
    order_item_id: { generated: false, required: true },
    payment_id: { generated: false, required: false },
    supplier_agorot: { generated: false, required: true },
    supplier_id: { generated: false, required: true },
    updated_at: { generated: false, required: false },
  },
  vouchers: {
    cancelled_at: { generated: false, required: false },
    code: { generated: false, required: true },
    coupon_price_agorot: { generated: false, required: true },
    created_at: { generated: false, required: false },
    expires_at: { generated: false, required: true },
    face_value_agorot: { generated: false, required: true },
    gift_claim_token_hash: { generated: false, required: false },
    gift_claimed_at: { generated: false, required: false },
    gift_message: { generated: false, required: false },
    gift_recipient_email: { generated: false, required: false },
    gift_recipient_name: { generated: false, required: false },
    gift_sent_at: { generated: false, required: false },
    gifted_by_user_id: { generated: false, required: false },
    id: { generated: false, required: false },
    issued_at: { generated: false, required: false },
    offer_valid_until: { generated: false, required: true },
    order_id: { generated: false, required: true },
    order_item_id: { generated: false, required: true },
    platform_percent: { generated: false, required: true },
    product_id: { generated: false, required: true },
    qr_key_id: { generated: false, required: false },
    qr_payload: { generated: false, required: true },
    redeemed_amount_collected_agorot: { generated: false, required: false },
    redeemed_at: { generated: false, required: false },
    redeemed_by_supplier_id: { generated: false, required: false },
    redeemed_by_user_id: { generated: false, required: false },
    refunded_at: { generated: false, required: false },
    remaining_amount_due_agorot: { generated: false, required: true },
    status: { generated: false, required: false },
    status_reason: { generated: false, required: false },
    supplier_id: { generated: false, required: true },
    updated_at: { generated: false, required: false },
    user_id: { generated: false, required: true },
  },
  wallet_accounts: {
    balance_ils: { generated: false, required: false },
    balance_ils_agorot: { generated: true, required: false },
    code: { generated: false, required: false },
    created_at: { generated: false, required: false },
    id: { generated: false, required: false },
    updated_at: { generated: false, required: false },
    user_id: { generated: false, required: false },
  },
}

/**
 * Identity arguments per overload. finalize passes arguments by name through
 * PostgREST, so a renamed parameter is a 42883 "function does not exist" on
 * the first paid order, not a type error.
 */
export const HOSTED_RPCS: Record<string, string[][]> = {
  consume_order_discount: [['p_order_id']],
  consume_order_stock: [['p_order_id']],
  fn_attribute_cart_recovery: [['p_order_id', 'p_user_id']],
  fn_enqueue_notification: [
    ['p_kind', 'p_email', 'p_dedupe', 'p_payload'],
    ['p_kind', 'p_email', 'p_dedupe', 'p_payload', 'p_user_id'],
  ],
  fn_wallet_transfer: [
    [
      'p_debit_account',
      'p_credit_account',
      'p_amount_ils',
      'p_reason',
      'p_idempotency',
      'p_order_id',
    ],
  ],
}
