'use client'

import SmartImage from '@/components/ui/SmartImage'
import { ELECTRO_HERO } from '@/lib/electro-hero-tokens'
import { HERO_SLIDER_BG } from '@/lib/hero-singlefile-data'
import { getImageProps } from 'next/image'
import { useCallback, useEffect, useState } from 'react'

export type HeroSlideImageLayout = {
  offsetTop: number
  widthPercent: number
  minHeight?: number
  /**
   * How far the image box sits in from the slider's inline start, as a percent
   * of slider width. The slider is `dir="rtl"`, so inline start is the RIGHT
   * edge, and until this existed the box was always flush against it. Live's
   * welcome slide is not flush: its image stops 86px short of the right edge in
   * a 728px slider, 11.8%. Every declared number can be correct and the image
   * still lands somewhere else without this one. Defaults to 0, so slides that
   * do not set it render exactly as before.
   */
  insetPercent?: number
}

export type HeroSlide = {
  id: string
  variant: 'welcome' | 'product' | 'app'
  title: string | null
  title_secondary?: string | null
  /** rs-layer xo:78 — second headline indented */
  title_secondary_indent?: boolean
  /** rs-layer xo:52 — first headline indented (תצוגה slide) */
  title_indent?: boolean
  tagline?: string | null
  standard_line?: string | null
  promo_small?: string | null
  promo_large?: string | null
  price_label?: string | null
  price?: string | null
  /** @deprecated use tagline */
  subtitle?: string | null
  image_url: string | null
  badge_image_url?: string | null
  link_url: string | null
  imageLayout?: HeroSlideImageLayout
}

const T = ELECTRO_HERO.typography
const SLIDE = ELECTRO_HERO.slider
const DOT_ACTIVE = 'var(--color-brand-primary)'
const DOT_INACTIVE = 'rgba(125, 125, 125, 0.5)'

// Live slider geometry: an 8px round dot, 30x8 rounded bar for the current one.
const DOT_HEIGHT = 8
const DOT_WIDTH_CURRENT = 30
const DOT_WIDTH_IDLE = 8
/**
 * Animated WebP files under /public. A file extension cannot tell an animated
 * WebP from a still one, so the ones we ship animated are listed explicitly.
 */
export const ANIMATED_WEBP_SOURCES = new Set([
  '/images/hero/slider/ios13-iphone-11pro-airpods-pro-setup-animation-steps.webp',
])

/**
 * The still frame each animated source falls back to below the desktop
 * breakpoint. Generated by scripts/hero-still-frame.mjs, which also records why
 * frame 0 is the right frame.
 *
 * This exists because an animated source is a hole in the image pipeline: it is
 * `unoptimized`, so it ships its full authored weight to every viewport. The
 * steps file is 777KB while every other image on the homepage leaves the
 * optimizer between 56KB and 97KB, and a mobile Lighthouse run put the
 * homepage's LCP at 10.1s with a TBT of 80ms and a CLS of 0 - that one file was
 * all that separated the page from 90+. A still IS optimizable, so below 1024px
 * next/image resizes it to what the box actually renders.
 *
 * A source with no entry here keeps the old behaviour exactly.
 */
export const HERO_STILL_FRAMES: Record<string, string> = {
  '/images/hero/slider/ios13-iphone-11pro-airpods-pro-setup-animation-steps.webp':
    '/images/hero/slider/ios13-iphone-11pro-airpods-pro-setup-animation-still.webp',
}

/**
 * Above this width the animation plays, below it the still is served. It is the
 * same 1024px boundary the slide markup already switches its image box at, so
 * the desktop layout that was measured against the live site does not move.
 */
const HERO_ANIMATION_MEDIA = '(min-width: 1024px)'

/** WCAG 2.2 / Lighthouse minimum tap target. */
const TAP_MIN = 24

const dotWidth = (isCurrent: boolean) => (isCurrent ? DOT_WIDTH_CURRENT : DOT_WIDTH_IDLE)
/** The button never shrinks below the tap minimum, and never below the dot. */
const dotButtonSize = (visible: number) => Math.max(TAP_MIN, visible)
/** Half the growth, handed back as negative margin so layout does not shift. */
const dotInset = (visible: number) => (dotButtonSize(visible) - visible) / 2
const AUTOPLAY_MS = 5000

/**
 * The rs-layer type ramp, measured off the live Revolution Slider at both
 * breakpoints. Every number below appeared inline three or four times across
 * the three slide variants; naming each ramp once means a remeasure edits one
 * line instead of hunting for repeats.
 *
 * These stay component-local rather than becoming @theme tokens because each
 * value is used only by this slider. A token in globals.css claims a value is
 * part of the site's scale; these are one component's measurements.
 */
const RS = {
  /** headline 1: rs-layer .tp-caption headline */
  h1: 'text-[43px] font-light lg:text-[58px]',
  h1Leading: 'leading-[43px] lg:leading-[58px]',
  /** headline 2: the lighter second line, always 5px shy of h1 */
  h2: 'text-[38px] font-light lg:text-[51px]',
  h2Leading: 'leading-[38px] lg:leading-[51px]',
  /** tagline strip under the headlines */
  tagline: 'text-[11px] font-bold leading-[11px] lg:text-[19px] lg:leading-[19px]',
  /** "standard" caption line (product slide only) */
  standard: 'text-[11px] font-bold leading-[15px] lg:text-[15px]',
  /** small promo line above the big price */
  promoSmall: 'text-[12px] leading-[13px] lg:text-[13px]',
  promoSmallWelcome: 'text-[12px] font-normal leading-[15px] lg:text-[15px]',
  /** the big promo price */
  promoLarge: 'text-[35px] font-bold leading-[35px] lg:text-[50px] lg:leading-[50px]',
  promoLargeWelcome: 'text-[35px] font-bold leading-[40px] lg:text-[45px] lg:leading-[50px]',
  /** copy column: 31px gutter from the slide edge */
  /**
   * `hero-copy-column` and `hero-headline` are hooks for the handheld override
   * in src/styles/home-handheld.css. The 50% column and the nowrap headlines
   * are 1440px measurements and overflow a phone viewport; the override
   * releases both below 1024px and changes nothing above it.
   */
  copyColumn:
    'hero-copy-column pointer-events-none absolute end-0 top-0 z-10 max-w-[50%] pe-[31px] text-end',
  /** headline box reserves its live height so shorter titles do not reflow */
  headBox: 'm-0 min-h-[86px] lg:min-h-[118px]',
  /** headline 2 rides -1px tighter than headline 1 on every variant */
  h2Tracking: '-1px',
  /** app slide: headline starts 52px down, badge is a fixed 46x286 box */
  appHeadOffset: 'mt-[52px]',
  badgeBox: 'h-[46px] w-[286px]',
  /**
   * The badge slot in CSS pixels. It used to say 572px, "2x the badge width so
   * the 2x raster is fetched", which double-counts: `sizes` is the CSS width of
   * the slot and the browser multiplies by devicePixelRatio itself, so a 2x
   * value asks a 2x screen for 4x. Byte-neutral for this one asset - the source
   * is 537px wide, so both 1080 and 640 come back as the same 537px file - and
   * corrected anyway, because the next badge that ships larger than 537px would
   * pay for the mistake with no signal.
   */
  badgeSizes: '286px',
  /** welcome slide insets its two promo lines by different amounts */
  promoSmallInset: 'ps-[11px]',
  promoLargeInset: 'ps-[10px]',
  /** rs-layer xo offsets: three distinct measured indents */
  indentSm: 'pe-[21px]',
  indentMd: 'pe-[47px]',
  indentLg: 'pe-[70px]',
} as const

/**
 * The welcome slide's own headline ramp, measured on kenyonexpress.co.il
 * 2026-07-30, not on the electro demo the shared RS ramp came from:
 *
 *   ברוכים הבאים   51px / 51px / weight 300 / white-space: nowrap
 *   לקניון Express 45px / 45px / weight 300 / white-space: nowrap
 *
 * At the shared 58/51 the second line no longer fits the 50% copy column and
 * wrapped to a third line, which pushed the tagline, SIMPLY THE and BEST down
 * by a whole line and was most of what was left of the y200-700 band difference
 * once the slider box itself matched. nowrap is what live uses; without it the
 * wrap comes back at any size the column cannot hold.
 */
const WELCOME_HEAD = {
  line1: 'text-[43px] leading-[43px] lg:text-[51px] lg:leading-[51px]',
  line2: 'text-[38px] leading-[38px] lg:text-[45px] lg:leading-[45px]',
} as const

/**
 * What the four non-animated slides paint, which is not the 100vw they used to
 * declare. They sit in the same handheld box as the still - full width but only
 * `h-[42%]` of the slider - and the frames are near-square under
 * `object-contain`, so HEIGHT is the constraint here too.
 *
 * Measured on this build at 320/360/390/412/768/1023: the box is 177px tall at
 * every one of them, so the painted width is CONSTANT - 193px for three of the
 * frames and 174px for the fourth. The number below is the widest of the four,
 * so the narrow one is over-served by 19px rather than any of them under-served.
 *
 * At 100vw a 412px phone at dpr 1.75 asked for 750px to paint 193.
 */
const HERO_SLIDE_HANDHELD_WIDTH = 193

const HERO_IMAGE_SIZES = `(max-width: 1024px) ${HERO_SLIDE_HANDHELD_WIDTH}px, ${SLIDE.width * 2}px`

/**
 * What the still actually occupies, which is nothing like the 100vw the shared
 * ramp declares. The handheld image box is full width but only `h-[42%]` of the
 * slider, and the frame is portrait (740x990) under `object-contain`, so HEIGHT
 * is the constraint and the painted image is far narrower than the viewport.
 *
 * Measured against this build at six widths: the box comes out 177px tall at
 * every one of them, so the painted image is a CONSTANT 132px wide from 320px
 * through 1023px.
 *
 * This said 42vw, on the reasoning that next/image only opens its small
 * `imageSizes` rungs when `sizes` carries a vw unit and that a flat px would be
 * held to `deviceSizes`, whose smallest rung is 640. **That is the opposite of
 * what this version does.** In next 16.2.4, `getWidths` in
 * next/dist/shared/lib/get-img-props.js returns the FULL ramp for a `sizes`
 * with no vw in it, and filters it to `>= deviceSizes[0] * smallestRatio` when
 * there is one - so 42vw was the thing cutting 256 off the ramp (640 * 0.42 =
 * 268.8) and handing a 132px box a 384px file. Stated flat, it gets 256.
 */
const HERO_STILL_HANDHELD_WIDTH = 132

const HERO_STILL_SIZES = `(min-width: 1024px) ${SLIDE.width * 2}px, ${HERO_STILL_HANDHELD_WIDTH}px`

const HERO_IMAGE_CLASS = 'min-h-full min-w-full object-contain object-center'

/**
 * The one animated slide, art-directed: animation on desktop, still on handheld.
 *
 * `<picture>` rather than two rendered images, because that is the only shape
 * where the browser fetches ONE of them. Two `<Image>` elements toggled with
 * `hidden lg:block` both download - a `display:none` ancestor does not stop an
 * eager fetch - so the phone would have paid the 777KB anyway and then paid for
 * the still on top of it.
 *
 * The `<img>` carries `loading="eager"` and `fetchPriority="high"` rather than
 * next/image's `preload`, because next/image would preload the STILL and the
 * desktop never renders it. The desktop preload is emitted by hand below with a
 * `media` attribute, which is the one thing next/image cannot express: a plain
 * preload of one variant is a download the other viewport throws away.
 */
function ArtDirectedHeroImage({
  animated,
  still,
  priority,
}: {
  animated: string
  still: string
  priority: boolean
}) {
  const {
    props: { srcSet: stillSrcSet, ...rest },
  } = getImageProps({
    src: still,
    alt: '',
    fill: true,
    quality: 90,
    sizes: HERO_STILL_SIZES,
    className: HERO_IMAGE_CLASS,
  })

  return (
    <picture>
      {/*
        The animated file goes in RAW, not through getImageProps. Asking it for
        an `unoptimized` source returns `srcSet: undefined`, and a <source> with
        no srcset still MATCHES its media query - it just resolves to nothing.
        Measured on the first build of this change: at 1440px the browser picked
        that empty source and the slide rendered a 1x1, so the desktop lost its
        animation while reporting no error at all. There is nothing for the
        optimizer to compute here anyway: an animated source is passed through
        byte-for-byte, so its only candidate is its own URL.
      */}
      <source media={HERO_ANIMATION_MEDIA} srcSet={animated} type="image/webp" />
      <img
        {...rest}
        // Already in `rest`, restated because the slide image is decorative
        // and a lint rule cannot read an alt that arrives through a spread.
        alt=""
        srcSet={stillSrcSet}
        loading={priority ? 'eager' : 'lazy'}
        fetchPriority={priority ? 'high' : undefined}
        decoding="async"
      />
    </picture>
  )
}

/**
 * The desktop preload that next/image's `priority` used to emit, put back by
 * hand. Without it the LCP image of the widest layout is discovered in the body
 * instead of the head, which is the thing `priority` existed to prevent.
 *
 * `media` is the reason this can exist at all, and the reason next/image cannot
 * emit it: `preload` on the component would preload whichever single variant it
 * was given, so it would either pull all 777KB onto every phone - the exact
 * thing this component is here to stop - or preload a still the desktop never
 * paints. It lives one level above ArtDirectedHeroImage because the slide
 * renders that twice, once per breakpoint box, and two identical preloads is one
 * more than the head needs.
 *
 * It is NOT what decides which animation frame a screenshot catches. That was
 * checked directly, because the homepage pixel comparison flips between the iOS
 * home screen and the black end-frame across builds and it looks alarming: the
 * file is an infinite 17.4s loop that holds frame 0 for exactly its first 5s,
 * and scripts/compare.mjs shoots at 6s. Adding this preload back did not move
 * the flip. Every band outside the image box compares 0%, and the desktop was
 * sampled at 1s intervals through 6 distinct frames, so the slide animates and
 * nothing has moved - the harness is just landing one second past a five second
 * hold.
 */
function HeroAnimationPreload({ src }: { src: string }) {
  return (
    <link rel="preload" as="image" href={src} media={HERO_ANIMATION_MEDIA} fetchPriority="high" />
  )
}

function HeroSlideImage({ src, priority }: { src: string; priority: boolean }) {
  // next/image cannot resize an animated image without dropping the animation,
  // so it detects one and streams the original bytes through untouched. That is
  // why the hero slide is authored at exactly 2x its rendered size: the
  // optimizer will not do it for us. Marking animated sources unoptimized skips
  // a round trip that provably returns the file unchanged (verified: 47 frames
  // in, 47 frames and the same byte count out).
  //
  // This used to test only `.gif`, which silently stopped matching when the
  // 4.5MB GIF became an animated WebP.
  const isAnimated = /\.gif$/i.test(src) || ANIMATED_WEBP_SOURCES.has(src)
  const still = HERO_STILL_FRAMES[src]

  if (isAnimated && still) {
    return <ArtDirectedHeroImage animated={src} still={still} priority={priority} />
  }

  return (
    <SmartImage
      src={src}
      alt=""
      fill
      priority={priority}
      quality={95}
      sizes={HERO_IMAGE_SIZES}
      unoptimized={isAnimated}
      className={HERO_IMAGE_CLASS}
      fallbackClassName="absolute inset-0"
      iconSize={48}
    />
  )
}

function SlideImage({
  slide,
  priority,
}: {
  slide: HeroSlide
  priority: boolean
}) {
  if (!slide.image_url) return null

  const layout = slide.imageLayout ?? {
    offsetTop: ELECTRO_HERO.slider.image.offsetTop,
    widthPercent: ELECTRO_HERO.slider.image.widthPercent,
    minHeight: ELECTRO_HERO.slider.image.height,
  }

  return (
    <>
      {priority && HERO_STILL_FRAMES[slide.image_url] && (
        <HeroAnimationPreload src={slide.image_url} />
      )}
      <div
        className="absolute hidden overflow-hidden lg:block"
        style={{
          top: layout.offsetTop,
          insetInlineStart: `${layout.insetPercent ?? 0}%`,
          width: `${layout.widthPercent}%`,
          height: SLIDE.height - Math.max(0, layout.offsetTop),
        }}
      >
        <div className="relative h-full w-full" style={{ minHeight: layout.minHeight }}>
          <HeroSlideImage src={slide.image_url} priority={priority} />
        </div>
      </div>
      <div className="absolute end-0 bottom-0 h-[42%] w-full overflow-hidden lg:hidden">
        <HeroSlideImage src={slide.image_url} priority={priority} />
      </div>
    </>
  )
}

function AppSlideCopy({ slide }: { slide: HeroSlide }) {
  return (
    <div className={`${RS.copyColumn} w-1/2`}>
      {slide.title && (
        <span
          style={{ color: T.headline1.color }}
          className={`${RS.appHeadOffset} block ${RS.h1} ${RS.h1Leading}`}
        >
          {slide.title}
        </span>
      )}
      {slide.title_secondary && (
        <span
          style={{ color: T.headline2.color, letterSpacing: RS.h2Tracking }}
          className={`mt-0 block ${RS.h2} ${RS.h2Leading} ${
            slide.title_secondary_indent ? RS.indentLg : ''
          }`}
        >
          {slide.title_secondary}
        </span>
      )}
      {slide.badge_image_url && (
        <div className={`relative ms-auto mt-16 max-w-full lg:mt-24 ${RS.badgeBox}`}>
          <SmartImage
            src={slide.badge_image_url}
            alt=""
            fill
            sizes={RS.badgeSizes}
            quality={90}
            className="object-contain object-left"
            fallbackClassName="absolute inset-0"
          />
        </div>
      )}
    </div>
  )
}

function ProductSlideCopy({ slide }: { slide: HeroSlide }) {
  const tagline = slide.tagline ?? slide.subtitle
  const line1Class = slide.title_indent ? RS.indentSm : ''

  return (
    <div
      className={`${RS.copyColumn} w-full pb-12 lg:w-1/2`}
      style={{ paddingTop: SLIDE.text.paddingTop }}
    >
      {(slide.title || slide.title_secondary) && (
        <h1 className={RS.headBox}>
          {slide.title && (
            <span
              style={{ color: T.headline1.color }}
              className={`block ${RS.h1} leading-[1.08] ${line1Class}`}
            >
              {slide.title}
            </span>
          )}
          {slide.title_secondary && (
            <span
              style={{ color: T.headline2.color, letterSpacing: RS.h2Tracking }}
              className={`mt-0.5 block ${RS.h2} leading-[1.08] lg:mt-1 ${
                slide.title_secondary_indent ? RS.indentMd : ''
              }`}
            >
              {slide.title_secondary}
            </span>
          )}
        </h1>
      )}

      {tagline && (
        <p style={{ color: T.tagline.color }} className={`mt-3 lg:mt-4 ${RS.tagline}`}>
          {tagline}
        </p>
      )}

      {slide.standard_line && (
        <p
          dir="ltr"
          style={{ color: T.headline1.color }}
          className={`mt-4 text-start lg:mt-5 ${RS.standard}`}
        >
          {slide.standard_line}
        </p>
      )}

      {slide.promo_small && (
        <p
          dir="ltr"
          style={{ color: T.priceLabel.color }}
          className={`mt-2 text-start lg:mt-3 ${RS.promoSmall}`}
        >
          {slide.promo_small}
        </p>
      )}

      {slide.promo_large && (
        <p
          dir="ltr"
          style={{ color: T.price.color }}
          className={`mt-0 text-start ${RS.promoLarge}`}
        >
          {slide.promo_large}
        </p>
      )}
    </div>
  )
}

function WelcomeSlideCopy({ slide }: { slide: HeroSlide }) {
  return (
    <div
      className={`${RS.copyColumn} w-full pb-12 lg:w-1/2`}
      style={{ paddingTop: SLIDE.text.paddingTop }}
    >
      <h1 className={RS.headBox}>
        {slide.title && (
          <span
            style={{ color: T.headline1.color }}
            className={`hero-headline block whitespace-nowrap font-light ${WELCOME_HEAD.line1}`}
          >
            {slide.title}
          </span>
        )}
        {slide.title_secondary && (
          <span
            style={{ color: T.headline2.color, letterSpacing: RS.h2Tracking }}
            className={`hero-headline mt-0.5 block whitespace-nowrap font-light lg:mt-1 ${WELCOME_HEAD.line2} ${
              slide.title_secondary_indent ? RS.indentMd : ''
            }`}
          >
            {slide.title_secondary}
          </span>
        )}
      </h1>
      {slide.tagline && (
        <p style={{ color: T.tagline.color }} className={`mt-4 lg:mt-5 ${RS.tagline}`}>
          {slide.tagline}
        </p>
      )}
      {slide.promo_small && (
        <p
          dir="ltr"
          style={{ color: T.headline1.color }}
          className={`mt-3 text-start lg:mt-4 ${RS.promoSmallInset} ${RS.promoSmallWelcome}`}
        >
          {slide.promo_small}
        </p>
      )}
      {slide.promo_large && (
        <p
          dir="ltr"
          style={{ color: T.price.color }}
          className={`mt-0 text-start ${RS.promoLargeInset} ${RS.promoLargeWelcome}`}
        >
          {slide.promo_large}
        </p>
      )}
    </div>
  )
}

function SlideCopy({ slide }: { slide: HeroSlide }) {
  if (slide.variant === 'app') return <AppSlideCopy slide={slide} />
  if (slide.variant === 'welcome') return <WelcomeSlideCopy slide={slide} />
  return <ProductSlideCopy slide={slide} />
}

export default function HeroSlider({ slides }: { slides: HeroSlide[] }) {
  // Start on the FIRST slide, which is what kenyonexpress.co.il does.
  //
  // This used to open on rs-19, the fifth slide, because that was the one left
  // active inside refs/ke_live_singlefile.html and the pixel comparison ran
  // against that snapshot. The reference moved to the live site (see the note at
  // the top of scripts/compare.mjs) and this initialiser did not follow, so the
  // hero was deterministically one slide apart from its own reference: live
  // showed `ברוכים הבאים לקניון Express`, we showed the app slide. It read as a
  // 24-31% band difference across y200-700 and looked like a layout defect.
  const [active, setActive] = useState(0)
  const [paused, setPaused] = useState(false)

  const goTo = useCallback(
    (index: number) => {
      if (slides.length === 0) return
      setActive(((index % slides.length) + slides.length) % slides.length)
    },
    [slides.length],
  )

  useEffect(() => {
    if (slides.length <= 1 || paused) return
    const t = setInterval(() => goTo(active + 1), AUTOPLAY_MS)
    return () => clearInterval(t)
  }, [active, goTo, paused, slides.length])

  if (slides.length === 0) return null

  return (
    // data-hero-slider is a stable hook for tooling. scripts/compare.mjs has to
    // hold a slide still before it screenshots, and it does that through the
    // pointer-enter pause below rather than by reaching into React state. It was
    // matching on [class*="hero"], which this root does not carry, so the pause
    // silently never fired and every local screenshot was taken one slide further
    // along than live's.
    <div
      dir="rtl"
      data-hero-slider=""
      style={{ backgroundColor: HERO_SLIDER_BG }}
      className="relative h-full min-h-0 w-full min-w-0 flex-1 overflow-hidden border-x border-gray-200 font-sans"
      onMouseEnter={() => setPaused(true)}
      onMouseLeave={() => setPaused(false)}
      onFocus={() => setPaused(true)}
      onBlur={() => setPaused(false)}
    >
      {slides.map((slide, i) => {
        const isActive = i === active

        return (
          <div
            key={slide.id}
            aria-hidden={!isActive}
            className={`absolute inset-0 transition-opacity duration-700 ease-in-out ${
              isActive ? 'z-10 opacity-100' : 'pointer-events-none z-0 opacity-0'
            }`}
          >
            <SlideImage slide={slide} priority={isActive && i === 0} />
            <div className="[&_*]:!animate-none [&_*]:!transition-none">
              <SlideCopy slide={slide} />
            </div>
          </div>
        )
      })}

      {slides.length > 1 && (
        <div
          aria-label="ניווט שקופיות"
          className="absolute bottom-6 left-1/2 z-20 flex -translate-x-1/2 items-center gap-2"
        >
          {slides.map((s, i) => {
            const isCurrent = i === active
            return (
              <button
                key={s.id}
                type="button"
                onClick={() => goTo(i)}
                aria-label={`שקופית ${i + 1}`}
                aria-current={isCurrent ? 'true' : undefined}
                style={{
                  // The dot is 8px because that is what the live slider renders.
                  // A 24px minimum tap target and an 8px dot are not in conflict
                  // if the BUTTON is 24px and its extra size is given back as
                  // negative margin: the hit area grows, the visible dot and
                  // every neighbour's position stay exactly where they were, so
                  // the pixel diff against live does not move.
                  width: dotButtonSize(dotWidth(isCurrent)),
                  height: dotButtonSize(DOT_HEIGHT),
                  marginInline: -dotInset(dotWidth(isCurrent)),
                  marginBlock: -dotInset(DOT_HEIGHT),
                  background: 'transparent',
                }}
                className="flex shrink-0 items-center justify-center border-0 p-0"
              >
                <span
                  aria-hidden="true"
                  style={{
                    width: dotWidth(isCurrent),
                    height: DOT_HEIGHT,
                    backgroundColor: isCurrent ? DOT_ACTIVE : DOT_INACTIVE,
                    borderRadius: isCurrent ? 3 : 9999,
                  }}
                  className="block transition-all duration-200 hover:opacity-80"
                />
              </button>
            )
          })}
        </div>
      )}
    </div>
  )
}
