'use client'

import SmartImage from '@/components/ui/SmartImage'
import { ELECTRO_HERO } from '@/lib/electro-hero-tokens'
import { HERO_SLIDER_BG } from '@/lib/hero-singlefile-data'
import { getImageProps } from 'next/image'
import { useCallback, useEffect, useState } from 'react'

export type HeroSlideImageLayout = {
  offsetTop: number
  widthPercent: number
  minHeight?: number
  /**
   * How far the image box sits in from the slider's inline start, as a percent
   * of slider width. The slider is `dir="rtl"`, so inline start is the RIGHT
   * edge, and until this existed the box was always flush against it. Live's
   * welcome slide is not flush: its image stops 86px short of the right edge in
   * a 728px slider, 11.8%. Every declared number can be correct and the image
   * still lands somewhere else without this one. Defaults to 0, so slides that
   * do not set it render exactly as before.
   */
  insetPercent?: number
}

export type HeroSlide = {
  id: string
  variant: 'welcome' | 'product' | 'app'
  title: string | null
  title_secondary?: string | null
  /** rs-layer xo:78 — second headline indented */
  title_secondary_indent?: boolean
  /** rs-layer xo:52 — first headline indented (תצוגה slide) */
  title_indent?: boolean
  tagline?: string | null
  standard_line?: string | null
  promo_small?: string | null
  promo_large?: string | null
  price_label?: string | null
  price?: string | null
  /** @deprecated use tagline */
  subtitle?: string | null
  image_url: string | null
  badge_image_url?: string | null
  link_url: string | null
  imageLayout?: HeroSlideImageLayout
}

const T = ELECTRO_HERO.typography
const SLIDE = ELECTRO_HERO.slider
const DOT_ACTIVE = 'var(--color-brand-primary)'
const DOT_INACTIVE = 'var(--color-slider-dot-idle)'

// Live slider geometry: an 8px round dot, 30x8 rounded bar for the current one.
const DOT_HEIGHT = 8
const DOT_WIDTH_CURRENT = 30
const DOT_WIDTH_IDLE = 8
/**
 * Animated WebP files under /public. A file extension cannot tell an animated
 * WebP from a still one, so the ones we ship animated are listed explicitly.
 */
export const ANIMATED_WEBP_SOURCES = new Set([
  '/images/hero/slider/ios13-iphone-11pro-airpods-pro-setup-animation-steps.webp',
])

/**
 * The still frame each animated source paints FIRST, on every viewport.
 * Generated by scripts/hero-still-frame.mjs, which also records why frame 0 is
 * the right frame. Below the desktop breakpoint it is all a visitor ever gets;
 * on desktop the animation swaps in over it once the page has loaded and the
 * file has finished downloading in the background.
 *
 * This exists because an animated source is a hole in the image pipeline: it is
 * `unoptimized`, so it ships its full authored weight to every viewport. The
 * steps file is 777KB while every other image on the homepage leaves the
 * optimizer between 56KB and 97KB, and a mobile Lighthouse run put the
 * homepage's LCP at 10.1s with a TBT of 80ms and a CLS of 0 - that one file was
 * all that separated the page from 90+. A still IS optimizable, so below 1024px
 * next/image resizes it to what the box actually renders.
 *
 * A source with no entry here keeps the old behaviour exactly.
 */
export const HERO_STILL_FRAMES: Record<string, string> = {
  '/images/hero/slider/ios13-iphone-11pro-airpods-pro-setup-animation-steps.webp':
    '/images/hero/slider/ios13-iphone-11pro-airpods-pro-setup-animation-still.webp',
}

/**
 * Above this width the animation plays, below it the still is served. It is the
 * same 1024px boundary the slide markup already switches its image box at, so
 * the desktop layout that was measured against the live site does not move.
 */
export const HERO_ANIMATION_MEDIA = '(min-width: 1024px)'

/** WCAG 2.2 / Lighthouse minimum tap target. */
const TAP_MIN = 24
/** The `gap-2` between the dots, in px. The inline insets below read it. */
const DOT_GAP = 8

const dotWidth = (isCurrent: boolean) => (isCurrent ? DOT_WIDTH_CURRENT : DOT_WIDTH_IDLE)
/** The button never shrinks below the tap minimum, and never below the dot. */
const dotButtonSize = (visible: number) => Math.max(TAP_MIN, visible)
/** Half the growth, handed back as negative margin so layout does not shift. */
const dotInset = (visible: number) => (dotButtonSize(visible) - visible) / 2

/**
 * THE SIDEWAYS GROWTH IS CAPPED, AND THE VERTICAL GROWTH IS NOT.
 *
 * Growing an 8px dot to a 24px button and handing the growth back as negative
 * margin keeps the layout still, but sideways it also walks the button into its
 * neighbour: 8px of inset on each side against an 8px gap left adjacent hit
 * areas overlapping by 8px, and hit testing gives an overlap to whichever
 * button comes later in the DOM. Measured on the home page 2026-08-19 (stage 8
 * Lighthouse, `target-size`): the buttons for slides 2 and 3 both claimed
 * x199..207, which is the left half of the VISIBLE dot for slide 2 — tapping
 * that dot opened slide 3.
 *
 * A neighbour can therefore only be met halfway. Capping each inline inset at
 * half the gap makes the hit areas touch and never overlap, and because the
 * button still gives back exactly what it grew, every dot stays where it was.
 *
 * That caps the idle dot at 16x24 rather than 24x24, so `target-size` still
 * reports it: 8px dots spaced 8px apart cannot host 24px targets without moving
 * them, and the spacing is measured off the live slider. WCAG 2.2's 2.5.8 is
 * outside the WCAG 2.1 AA set this project gates on (`e2e/a11y.spec.ts`), and
 * moving the dots is a pixel-fidelity decision for Ofir, recorded in
 * docs/LIGHTHOUSE-AUDIT.md. The wrong-slide tap is a defect either way, and it
 * is what this fixes. Vertically there is no neighbour, so the full 24px
 * stands.
 */
const dotInsetInline = (visible: number) => Math.min(dotInset(visible), DOT_GAP / 2)
export const dotButtonWidth = (visible: number) => visible + 2 * dotInsetInline(visible)
export const dotHitBox = (visible: number) => ({
  width: dotButtonWidth(visible),
  height: dotButtonSize(DOT_HEIGHT),
  marginInline: -dotInsetInline(visible),
  marginBlock: -dotInset(DOT_HEIGHT),
})
export const HERO_DOT_GEOMETRY = {
  gap: DOT_GAP,
  idle: DOT_WIDTH_IDLE,
  current: DOT_WIDTH_CURRENT,
}
const AUTOPLAY_MS = 5000

/**
 * The rs-layer type ramp, measured off the live Revolution Slider at both
 * breakpoints. Every number below appeared inline three or four times across
 * the three slide variants; naming each ramp once means a remeasure edits one
 * line instead of hunting for repeats.
 *
 * These stay component-local rather than becoming @theme tokens because each
 * value is used only by this slider. A token in globals.css claims a value is
 * part of the site's scale; these are one component's measurements.
 */
const RS = {
  /** headline 1: rs-layer .tp-caption headline */
  // 51 at lg, remeasured off refs 2026-09-02 (live "Open Sans" 51px; 58 was the electro demo)
  h1: 'text-hero-line1 font-light lg:text-hero-line1-lg',
  h1Leading: 'leading-[43px] lg:leading-[58px]',
  /** headline 2: the lighter second line, always 5px shy of h1 */
  // 45 at lg, remeasured off refs 2026-09-02 (58/51 were the electro demo's sizes)
  h2: 'text-hero-line2 font-light lg:text-hero-line2-lg',
  h2Leading: 'leading-[38px] lg:leading-[51px]',
  /** tagline strip under the headlines */
  tagline: 'text-micro font-bold leading-[11px] lg:text-hero-tagline-lg lg:leading-[19px]',
  /** "standard" caption line (product slide only) */
  standard: 'text-micro font-bold leading-[15px] lg:text-body-lg',
  /** small promo line above the big price */
  promoSmall: 'text-tiny leading-[13px] lg:text-small',
  promoSmallWelcome: 'text-tiny font-normal leading-[15px] lg:text-body-lg',
  /** the big promo price */
  promoLarge: 'text-hero-promo font-bold leading-[35px] lg:text-hero-promo-lg lg:leading-[50px]',
  promoLargeWelcome:
    'text-hero-promo font-bold leading-[40px] lg:text-hero-promo-welcome-lg lg:leading-[50px]',
  /** copy column: 31px gutter from the slide edge */
  /**
   * `hero-copy-column` and `hero-headline` are hooks for the handheld override
   * in src/styles/home-handheld.css. The 50% column and the nowrap headlines
   * are 1440px measurements and overflow a phone viewport; the override
   * releases both below 1024px and changes nothing above it.
   */
  copyColumn:
    'hero-copy-column pointer-events-none absolute end-0 top-0 z-10 max-w-[50%] pe-[31px] text-end',
  /** headline box reserves its live height so shorter titles do not reflow */
  // 110 at lg: live's tagline top is 157 and the headline paddingTop is 47
  // (refs), so the reserved headline box is exactly 157-47 = 110. The old 118
  // plus the tagline's mt-4 pushed everything below the headline ~25px down.
  headBox: 'm-0 min-h-[86px] lg:min-h-[110px]',
  /** headline 2 rides -1px tighter than headline 1 on every variant */
  h2Tracking: '-1px',
  /** app slide: headline starts 52px down, badge is a fixed 46x286 box */
  appHeadOffset: 'mt-[52px]',
  badgeBox: 'h-[46px] w-[286px]',
  /**
   * The badge slot in CSS pixels. It used to say 572px, "2x the badge width so
   * the 2x raster is fetched", which double-counts: `sizes` is the CSS width of
   * the slot and the browser multiplies by devicePixelRatio itself, so a 2x
   * value asks a 2x screen for 4x. Byte-neutral for this one asset - the source
   * is 537px wide, so both 1080 and 640 come back as the same 537px file - and
   * corrected anyway, because the next badge that ships larger than 537px would
   * pay for the mistake with no signal.
   */
  badgeSizes: '286px',
  /** welcome slide insets its two promo lines by different amounts */
  promoSmallInset: 'ps-[11px]',
  promoLargeInset: 'ps-[10px]',
  /** rs-layer xo offsets: three distinct measured indents */
  indentSm: 'pe-[21px]',
  indentMd: 'pe-[47px]',
  indentLg: 'pe-[70px]',
} as const

/**
 * The welcome slide's own headline ramp, measured on kenyonexpress.co.il
 * 2026-07-30, not on the electro demo the shared RS ramp came from:
 *
 *   ברוכים הבאים   51px / 51px / weight 300 / white-space: nowrap
 *   לקניון Express 45px / 45px / weight 300 / white-space: nowrap
 *
 * At the shared 58/51 the second line no longer fits the 50% copy column and
 * wrapped to a third line, which pushed the tagline, SIMPLY THE and BEST down
 * by a whole line and was most of what was left of the y200-700 band difference
 * once the slider box itself matched. nowrap is what live uses; without it the
 * wrap comes back at any size the column cannot hold.
 */
const WELCOME_HEAD = {
  line1: 'text-hero-line1 leading-[43px] lg:text-hero-line1-lg lg:leading-[51px]',
  line2: 'text-hero-line2 leading-[38px] lg:text-hero-line2-lg lg:leading-[45px]',
} as const

/**
 * What the four non-animated slides paint, which is not the 100vw they used to
 * declare. They sit in the same handheld box as the still - full width but only
 * `h-[42%]` of the slider - and the frames are near-square under
 * `object-contain`, so HEIGHT is the constraint here too.
 *
 * Measured on this build at 320/360/390/412/768/1023: the box is 177px tall at
 * every one of them, so the painted width is CONSTANT - 193px for three of the
 * frames and 174px for the fourth. The number below is the widest of the four,
 * so the narrow one is over-served by 19px rather than any of them under-served.
 *
 * At 100vw a 412px phone at dpr 1.75 asked for 750px to paint 193.
 */
const HERO_SLIDE_HANDHELD_WIDTH = 193

const HERO_IMAGE_SIZES = `(max-width: 1024px) ${HERO_SLIDE_HANDHELD_WIDTH}px, ${SLIDE.width * 2}px`

/**
 * What the still actually occupies, which is nothing like the 100vw the shared
 * ramp declares. The handheld image box is full width but only `h-[42%]` of the
 * slider, and the frame is portrait (740x990) under `object-contain`, so HEIGHT
 * is the constraint and the painted image is far narrower than the viewport.
 *
 * Measured against this build at six widths: the box comes out 177px tall at
 * every one of them, so the painted image is a CONSTANT 132px wide from 320px
 * through 1023px.
 *
 * This said 42vw, on the reasoning that next/image only opens its small
 * `imageSizes` rungs when `sizes` carries a vw unit and that a flat px would be
 * held to `deviceSizes`, whose smallest rung is 640. **That is the opposite of
 * what this version does.** In next 16.2.4, `getWidths` in
 * next/dist/shared/lib/get-img-props.js returns the FULL ramp for a `sizes`
 * with no vw in it, and filters it to `>= deviceSizes[0] * smallestRatio` when
 * there is one - so 42vw was the thing cutting 256 off the ramp (640 * 0.42 =
 * 268.8) and handing a 132px box a 384px file. Stated flat, it gets 256.
 */
const HERO_STILL_HANDHELD_WIDTH = 132

const HERO_STILL_SIZES = `(min-width: 1024px) ${SLIDE.width * 2}px, ${HERO_STILL_HANDHELD_WIDTH}px`

const HERO_IMAGE_CLASS = 'min-h-full min-w-full object-contain object-center'

/**
 * The one animated slide, art-directed: still first everywhere, animation
 * swapped in on desktop once the page has loaded.
 *
 * `<picture>` rather than two rendered images, because that is the only shape
 * where the browser fetches ONE of them. Two `<Image>` elements toggled with
 * `hidden lg:block` both download - a `display:none` ancestor does not stop an
 * eager fetch - so the phone would have paid the 777KB anyway and then paid for
 * the still on top of it.
 *
 * The animated `<source>` is NOT in the initial markup. It used to be, plus a
 * head preload at high priority, and that pair made the animation the desktop
 * LCP at 12.1-12.9s on slow 4G + cpu/4: the hero's first paint waited for all
 * 794404 bytes while the optimized still - a ninth of the weight - sat unused
 * below the breakpoint. Now every viewport paints the still, and the desktop
 * fetches the animation at LOW priority after `window` load, mounting the
 * `<source>` only when the file has fully arrived, so the swap is a decode of
 * bytes already in cache and never a blank box.
 *
 * The swap cannot move LCP, and this is load-bearing: both files are 740x990
 * in the same `object-contain` box, so the swapped-in frame paints the exact
 * rect the still already painted, and LCP only accepts candidates LARGER than
 * the current champion - the same mechanics the autoplay gate below is built
 * on. [16]'s trade still stands: desktop gets the animation, it just starts a
 * beat later. `prefers-reduced-motion` keeps the still, which a markup-only
 * `<source>` could never offer.
 *
 * The `<img>` carries `loading="eager"` and `fetchPriority="high"` for the
 * priority slide because the still is now the homepage's real first hero paint
 * on every viewport.
 */
export function ArtDirectedHeroImage({
  animated,
  still,
  priority,
}: {
  animated: string
  still: string
  priority: boolean
}) {
  const [animationReady, setAnimationReady] = useState(false)

  useEffect(() => {
    // Media guards, not CSS: below the breakpoint the animation must never be
    // FETCHED, which no amount of hiding can express. Reduced motion keeps the
    // still for the same reason - the request itself is the cost.
    if (!window.matchMedia(HERO_ANIMATION_MEDIA).matches) return
    if (window.matchMedia('(prefers-reduced-motion: reduce)').matches) return

    let disposed = false
    // Two instances run this (one per breakpoint box); same URL, so the second
    // fetch is a cache hit and both swap together.
    const fetchAnimation = () => {
      if (disposed) return
      const probe = new window.Image()
      probe.fetchPriority = 'low'
      probe.onload = () => {
        if (!disposed) setAnimationReady(true)
      }
      probe.src = animated
    }
    if (document.readyState === 'complete') {
      fetchAnimation()
    } else {
      window.addEventListener('load', fetchAnimation, { once: true })
    }
    return () => {
      disposed = true
      window.removeEventListener('load', fetchAnimation)
    }
  }, [animated])

  const {
    props: { srcSet: stillSrcSet, ...rest },
  } = getImageProps({
    src: still,
    alt: '',
    fill: true,
    quality: 90,
    sizes: HERO_STILL_SIZES,
    className: HERO_IMAGE_CLASS,
  })

  return (
    <picture>
      {/*
        The animated file goes in RAW, not through getImageProps. Asking it for
        an `unoptimized` source returns `srcSet: undefined`, and a <source> with
        no srcset still MATCHES its media query - it just resolves to nothing.
        Measured on the first build of [16]: at 1440px the browser picked that
        empty source and the slide rendered a 1x1, so the desktop lost its
        animation while reporting no error at all. There is nothing for the
        optimizer to compute here anyway: an animated source is passed through
        byte-for-byte, so its only candidate is its own URL.
      */}
      {animationReady && (
        <source media={HERO_ANIMATION_MEDIA} srcSet={animated} type="image/webp" />
      )}
      <img
        {...rest}
        // Already in `rest`, restated because the slide image is decorative
        // and a lint rule cannot read an alt that arrives through a spread.
        alt=""
        srcSet={stillSrcSet}
        loading={priority ? 'eager' : 'lazy'}
        fetchPriority={priority ? 'high' : undefined}
        decoding="async"
      />
    </picture>
  )
}

function HeroSlideImage({ src, priority }: { src: string; priority: boolean }) {
  // next/image cannot resize an animated image without dropping the animation,
  // so it detects one and streams the original bytes through untouched. That is
  // why the hero slide is authored at exactly 2x its rendered size: the
  // optimizer will not do it for us. Marking animated sources unoptimized skips
  // a round trip that provably returns the file unchanged (verified: 47 frames
  // in, 47 frames and the same byte count out).
  //
  // This used to test only `.gif`, which silently stopped matching when the
  // 4.5MB GIF became an animated WebP.
  const isAnimated = /\.gif$/i.test(src) || ANIMATED_WEBP_SOURCES.has(src)
  const still = HERO_STILL_FRAMES[src]

  if (isAnimated && still) {
    return <ArtDirectedHeroImage animated={src} still={still} priority={priority} />
  }

  return (
    <SmartImage
      src={src}
      alt=""
      fill
      priority={priority}
      quality={95}
      sizes={HERO_IMAGE_SIZES}
      unoptimized={isAnimated}
      className={HERO_IMAGE_CLASS}
      fallbackClassName="absolute inset-0"
      iconSize={48}
    />
  )
}

function SlideImage({
  slide,
  priority,
}: {
  slide: HeroSlide
  priority: boolean
}) {
  if (!slide.image_url) return null

  const layout = slide.imageLayout ?? {
    offsetTop: ELECTRO_HERO.slider.image.offsetTop,
    widthPercent: ELECTRO_HERO.slider.image.widthPercent,
    minHeight: ELECTRO_HERO.slider.image.height,
  }

  return (
    <>
      {/*
        Two boxes, one per breakpoint. Never mark BOTH priority: a `hidden`
        ancestor does not cancel an eager fetch, so a phone was downloading the
        desktop raster (and a desktop the phone one) for the same slide. The
        visible box gets `priority`; the other stays lazy and typically does not
        fetch while `display:none`.
      */}
      <div
        className="absolute hidden overflow-hidden lg:block"
        style={{
          top: layout.offsetTop,
          insetInlineStart: `${layout.insetPercent ?? 0}%`,
          width: `${layout.widthPercent}%`,
          height: SLIDE.height - Math.max(0, layout.offsetTop),
        }}
      >
        <div className="relative h-full w-full" style={{ minHeight: layout.minHeight }}>
          <HeroSlideImage src={slide.image_url} priority={false} />
        </div>
      </div>
      <div className="absolute end-0 bottom-0 h-[42%] w-full overflow-hidden lg:hidden">
        <HeroSlideImage src={slide.image_url} priority={priority} />
      </div>
    </>
  )
}

function AppSlideCopy({ slide, mountMedia }: { slide: HeroSlide; mountMedia: boolean }) {
  return (
    <div className={`${RS.copyColumn} w-1/2`}>
      {slide.title && (
        <span
          style={{ color: T.headline1.color }}
          className={`${RS.appHeadOffset} block ${RS.h1} ${RS.h1Leading}`}
        >
          {slide.title}
        </span>
      )}
      {slide.title_secondary && (
        <span
          style={{ color: T.headline2.color, letterSpacing: RS.h2Tracking }}
          className={`mt-0 block ${RS.h2} ${RS.h2Leading} ${
            slide.title_secondary_indent ? RS.indentLg : ''
          }`}
        >
          {slide.title_secondary}
        </span>
      )}
      {/*
        Same mount gate as SlideImage: the app badge lived in the copy tree, so
        opacity-0 on inactive slides still fetched Screen-Shot (~8KB) on every
        phone load and contended with the LCP still.
      */}
      {mountMedia && slide.badge_image_url ? (
        <div className={`relative ms-auto mt-16 max-w-full lg:mt-24 ${RS.badgeBox}`}>
          <SmartImage
            src={slide.badge_image_url}
            alt=""
            fill
            sizes={RS.badgeSizes}
            quality={90}
            className="object-contain object-left"
            fallbackClassName="absolute inset-0"
          />
        </div>
      ) : null}
    </div>
  )
}

function ProductSlideCopy({ slide }: { slide: HeroSlide }) {
  const tagline = slide.tagline ?? slide.subtitle
  const line1Class = slide.title_indent ? RS.indentSm : ''

  return (
    <div
      className={`${RS.copyColumn} w-full pb-12 lg:w-1/2`}
      style={{ paddingTop: SLIDE.text.paddingTop }}
    >
      {(slide.title || slide.title_secondary) && (
        <h1 className={RS.headBox}>
          {slide.title && (
            <span
              style={{ color: T.headline1.color }}
              className={`block ${RS.h1} leading-[1.08] ${line1Class}`}
            >
              {slide.title}
            </span>
          )}
          {slide.title_secondary && (
            <span
              style={{ color: T.headline2.color, letterSpacing: RS.h2Tracking }}
              className={`mt-0.5 block ${RS.h2} leading-[1.08] lg:mt-1 ${
                slide.title_secondary_indent ? RS.indentMd : ''
              }`}
            >
              {slide.title_secondary}
            </span>
          )}
        </h1>
      )}

      {tagline && (
        <p style={{ color: T.tagline.color }} className={`mt-3 lg:mt-0 ${RS.tagline}`}>
          {tagline}
        </p>
      )}

      {slide.standard_line && (
        <p
          dir="ltr"
          style={{ color: T.headline1.color }}
          className={`mt-4 text-start lg:mt-5 ${RS.standard}`}
        >
          {slide.standard_line}
        </p>
      )}

      {slide.promo_small && (
        <p
          dir="ltr"
          style={{ color: T.priceLabel.color }}
          className={`mt-2 text-start lg:mt-[27px] ${RS.promoSmall}`}
        >
          {slide.promo_small}
        </p>
      )}

      {slide.promo_large && (
        <p
          dir="ltr"
          style={{ color: T.price.color }}
          className={`mt-0 text-start ${RS.promoLarge}`}
        >
          {slide.promo_large}
        </p>
      )}
    </div>
  )
}

function WelcomeSlideCopy({ slide }: { slide: HeroSlide }) {
  return (
    <div
      className={`${RS.copyColumn} w-full pb-12 lg:w-1/2`}
      style={{ paddingTop: SLIDE.text.paddingTop }}
    >
      <h1 className={RS.headBox}>
        {slide.title && (
          <span
            style={{ color: T.headline1.color }}
            className={`hero-headline block whitespace-nowrap font-light ${WELCOME_HEAD.line1}`}
          >
            {slide.title}
          </span>
        )}
        {slide.title_secondary && (
          <span
            style={{ color: T.headline2.color, letterSpacing: RS.h2Tracking }}
            className={`hero-headline mt-0.5 block whitespace-nowrap font-light lg:mt-1 ${WELCOME_HEAD.line2} ${
              slide.title_secondary_indent ? RS.indentMd : ''
            }`}
          >
            {slide.title_secondary}
          </span>
        )}
      </h1>
      {slide.tagline && (
        <p style={{ color: T.tagline.color }} className={`mt-4 lg:mt-5 ${RS.tagline}`}>
          {slide.tagline}
        </p>
      )}
      {slide.promo_small && (
        <p
          dir="ltr"
          style={{ color: T.headline1.color }}
          className={`mt-3 text-start lg:mt-4 ${RS.promoSmallInset} ${RS.promoSmallWelcome}`}
        >
          {slide.promo_small}
        </p>
      )}
      {slide.promo_large && (
        <p
          dir="ltr"
          style={{ color: T.price.color }}
          className={`mt-0 text-start ${RS.promoLargeInset} ${RS.promoLargeWelcome}`}
        >
          {slide.promo_large}
        </p>
      )}
    </div>
  )
}

function SlideCopy({ slide, mountMedia }: { slide: HeroSlide; mountMedia: boolean }) {
  if (slide.variant === 'app') return <AppSlideCopy slide={slide} mountMedia={mountMedia} />
  if (slide.variant === 'welcome') return <WelcomeSlideCopy slide={slide} />
  return <ProductSlideCopy slide={slide} />
}

export default function HeroSlider({ slides }: { slides: HeroSlide[] }) {
  // Start on the FIRST slide, which is what kenyonexpress.co.il does.
  //
  // This used to open on rs-19, the fifth slide, because that was the one left
  // active inside refs/ke_live_singlefile.html and the pixel comparison ran
  // against that snapshot. The reference moved to the live site (see the note at
  // the top of scripts/compare.mjs) and this initialiser did not follow, so the
  // hero was deterministically one slide apart from its own reference: live
  // showed `ברוכים הבאים לקניון Express`, we showed the app slide. It read as a
  // 24-31% band difference across y200-700 and looked like a layout defect.
  const [active, setActive] = useState(0)
  const [paused, setPaused] = useState(false)
  const [engaged, setEngaged] = useState(false)

  const goTo = useCallback(
    (index: number) => {
      if (slides.length === 0) return
      setActive(((index % slides.length) + slides.length) % slides.length)
    },
    [slides.length],
  )

  /**
   * Autoplay waits for the visitor to press something. This is the home page's
   * LCP, and the reason is specific enough to be worth writing down in full.
   *
   * MEASURED on a 412px phone, real slow 4G + cpu/4 (scripts/_lcp-probe.mjs,
   * scripts/_hero-timing-probe.mjs), before this change:
   *
   *   900ms   banner paragraph paints. size 33553. LCP so far: 900ms.
   *   2451ms  slide 2's image finishes downloading. Nothing paints.
   *   9096ms  first autoplay tick reveals slide 2. size 33891. LCP: 9096ms.
   *
   * The image was ready six and a half seconds before it was shown. Nothing
   * was slow. The page simply revealed a larger element late, and LCP is
   * defined as the largest element's paint time, so the whole metric moved -
   * for a margin of 338 square pixels, ONE PERCENT, over the element that was
   * already on screen. Every configuration measured did the same thing:
   * 8992-9096ms for a new visitor, 9268ms for a returning one, 11440ms on a
   * 1440px desktop.
   *
   * Preloading cannot fix it, because the image was never the delay. Nor can a
   * longer interval: without user input LCP keeps accepting new candidates for
   * as long as the page lives, so any delay just moves the number. The only
   * thing that closes the window is input - LCP is final at the first click,
   * tap or key press, by definition - and that is exactly what this waits for.
   *
   * So: a visitor who lands and reads sees the slide the page was built around
   * and a fast LCP. A visitor who touches anything gets the carousel, starting
   * from the moment their interaction has already sealed the metric. There is
   * no arrangement in which both a rotating carousel and a fast LCP are true
   * for someone who never interacts, because the rotation IS a late large
   * paint; this picks which visitor pays, rather than pretending otherwise.
   *
   * `pointerdown`/`keydown` and not `scroll`: scrolling does NOT finalise LCP,
   * so starting on scroll would move the paint without closing the window and
   * would measure exactly as badly.
   */
  useEffect(() => {
    if (engaged) return
    const onInput = () => setEngaged(true)
    window.addEventListener('pointerdown', onInput, { passive: true })
    window.addEventListener('keydown', onInput, { passive: true })
    return () => {
      window.removeEventListener('pointerdown', onInput)
      window.removeEventListener('keydown', onInput)
    }
  }, [engaged])

  useEffect(() => {
    if (!engaged || slides.length <= 1 || paused) return
    const t = setInterval(() => goTo(active + 1), AUTOPLAY_MS)
    return () => clearInterval(t)
  }, [engaged, active, goTo, paused, slides.length])

  if (slides.length === 0) return null

  return (
    // data-hero-slider is a stable hook for tooling. scripts/compare.mjs has to
    // hold a slide still before it screenshots, and it does that through the
    // pointer-enter pause below rather than by reaching into React state. It was
    // matching on [class*="hero"], which this root does not carry, so the pause
    // silently never fired and every local screenshot was taken one slide further
    // along than live's.
    <div
      dir="rtl"
      data-hero-slider=""
      style={{ backgroundColor: HERO_SLIDER_BG }}
      className="relative h-full min-h-0 w-full min-w-0 flex-1 overflow-hidden border-x border-border-alt font-sans"
      onMouseEnter={() => setPaused(true)}
      onMouseLeave={() => setPaused(false)}
      onFocus={() => setPaused(true)}
      onBlur={() => setPaused(false)}
    >
      {slides.map((slide, i) => {
        const isActive = i === active
        // Until the visitor engages, only the first slide mounts its images.
        // Mounting every slide's <Image> (desktop + mobile boxes) still fetched
        // four extra rasters on a phone and contended with the LCP still.
        const mountMedia = isActive || engaged

        return (
          <div
            key={slide.id}
            aria-hidden={!isActive}
            className={`absolute inset-0 transition-opacity duration-700 ease-in-out ${
              isActive ? 'z-10 opacity-100' : 'pointer-events-none z-0 opacity-0'
            }`}
          >
            {mountMedia ? <SlideImage slide={slide} priority={isActive && i === 0} /> : null}
            <div className="[&_*]:!animate-none [&_*]:!transition-none">
              <SlideCopy slide={slide} mountMedia={mountMedia} />
            </div>
          </div>
        )
      })}

      {slides.length > 1 && (
        <div
          aria-label="ניווט שקופיות"
          // Live (refs, 1440): rs-bullets is a 200x8 box at x397 y400 -- 61px
          // from the slider's left edge, 252px from its top, bullets packed to
          // its right end with 15px gaps. Centered-at-bottom was ours, not
          // live's. Physical left/top because the measurements are physical.
          // On phones the mobile hero keeps the old centered-bottom row.
          className="absolute z-20 flex items-center max-lg:bottom-6 max-lg:left-1/2 max-lg:-translate-x-1/2 max-lg:gap-2 lg:top-[252px] lg:left-[61px] lg:w-[200px] lg:justify-end lg:gap-[15px]"
        >
          {slides.map((s, i) => {
            const isCurrent = i === active
            return (
              <button
                key={s.id}
                type="button"
                onClick={() => goTo(i)}
                aria-label={`שקופית ${i + 1}`}
                aria-current={isCurrent ? 'true' : undefined}
                style={{
                  // The dot is 8px because that is what the live slider renders.
                  // The button around it grows to the tap minimum and hands the
                  // growth back as negative margin, so the hit area grows while
                  // the visible dot and every neighbour stay where they were and
                  // the pixel diff against live does not move. Sideways the
                  // growth stops at half the gap; see dotInsetInline.
                  ...dotHitBox(dotWidth(isCurrent)),
                  background: 'transparent',
                }}
                className="flex shrink-0 items-center justify-center border-0 p-0 max-lg:min-w-6"
              >
                <span
                  aria-hidden="true"
                  style={{
                    width: dotWidth(isCurrent),
                    height: DOT_HEIGHT,
                    backgroundColor: isCurrent ? DOT_ACTIVE : DOT_INACTIVE,
                    borderRadius: isCurrent ? 3 : 9999,
                  }}
                  className="block transition-all duration-200 hover:opacity-80"
                />
              </button>
            )
          })}
        </div>
      )}
    </div>
  )
}
