// GENERATED by scripts/build-migration-manifest.mjs. Do not edit by hand.
//
// Regenerate:  node scripts/build-migration-manifest.mjs
// Gated by:    src/__tests__/pending-migrations-inventory.test.ts, which rebuilds
//              this list from the directories and fails when the two differ.
//
// It describes THE REPOSITORY, not the database. A row saying `pending` means
// nobody has approved that file; it does not prove production lacks the change,
// and `applied` is this repo's record of an apply that was verified at the time.
// The database's own answer lives in supabase_migrations.schema_migrations.

export type MigrationState = 'pending' | 'applied' | 'cancelled'

export interface MigrationEntry {
  number: string
  file: string
  state: MigrationState
  /** Pending files must ship with preflight_<n>.sql beside them. */
  hasPreflight: boolean
}

export const MIGRATION_MANIFEST: readonly MigrationEntry[] = [
  {
    number: '122',
    file: '122_deny_all_on_server_only_tables.sql',
    state: 'applied',
    hasPreflight: false,
  },
  {
    number: '123',
    file: '123_products_whatsapp_enabled.sql',
    state: 'applied',
    hasPreflight: false,
  },
  {
    number: '124',
    file: '124_categories_sort_order.sql',
    state: 'applied',
    hasPreflight: false,
  },
  {
    number: '125',
    file: '125_expire_vouchers_drop_escrow.sql',
    state: 'applied',
    hasPreflight: false,
  },
  {
    number: '126',
    file: '126_percent_range_checks.sql',
    state: 'applied',
    hasPreflight: false,
  },
  {
    number: '127',
    file: '127_homepage_cms.sql',
    state: 'applied',
    hasPreflight: false,
  },
  {
    number: '130',
    file: '130_payment_events.sql',
    state: 'applied',
    hasPreflight: false,
  },
  {
    number: '131',
    file: '131_refunds.sql',
    state: 'applied',
    hasPreflight: false,
  },
  {
    number: '132',
    file: '132_search_index_outbox.sql',
    state: 'applied',
    hasPreflight: false,
  },
  {
    number: '133',
    file: '133_supplier_branches.sql',
    state: 'applied',
    hasPreflight: false,
  },
  {
    number: '134',
    file: '134_order_items_delivered_at.sql',
    state: 'applied',
    hasPreflight: false,
  },
  {
    number: '135a',
    file: '135a_product_type_recurring.sql',
    state: 'applied',
    hasPreflight: false,
  },
  {
    number: '135b',
    file: '135b_recurring_subscriptions.sql',
    state: 'applied',
    hasPreflight: false,
  },
  {
    number: '136',
    file: '136_supplier_coordinates.sql',
    state: 'applied',
    hasPreflight: false,
  },
  {
    number: '137',
    file: '137_order_transition_guard.sql',
    state: 'applied',
    hasPreflight: false,
  },
  {
    number: '138',
    file: '138_money_agorot_money_path.sql',
    state: 'applied',
    hasPreflight: false,
  },
  {
    number: '139',
    file: '139_money_agorot_wallet.sql',
    state: 'applied',
    hasPreflight: false,
  },
  {
    number: '140',
    file: '140_money_agorot_catalog.sql',
    state: 'applied',
    hasPreflight: false,
  },
  {
    number: '141',
    file: '141_money_agorot_growth.sql',
    state: 'applied',
    hasPreflight: false,
  },
  {
    number: '143',
    file: '143_revoke_unused_definer_execute.sql',
    state: 'applied',
    hasPreflight: false,
  },
  {
    number: '144',
    file: '144_revoke_authenticated_dml.sql',
    state: 'applied',
    hasPreflight: false,
  },
  {
    number: '145',
    file: '145_revoke_check_rate_limit_execute.sql',
    state: 'applied',
    hasPreflight: false,
  },
  {
    number: '146',
    file: '146_wallet_balance_floor.sql',
    state: 'applied',
    hasPreflight: false,
  },
  {
    number: '147',
    file: '147_money_agorot_remaining_twins.sql',
    state: 'applied',
    hasPreflight: false,
  },
  {
    number: '148',
    file: '148_refund_destination.sql',
    state: 'applied',
    hasPreflight: false,
  },
  {
    number: '149',
    file: '149_audit_log_append_only.sql',
    state: 'applied',
    hasPreflight: false,
  },
  {
    number: '150',
    file: '150_account_deletion.sql',
    state: 'applied',
    hasPreflight: false,
  },
  {
    number: '151',
    file: '151_analytics_ingest.sql',
    state: 'applied',
    hasPreflight: false,
  },
  {
    number: '152',
    file: '152_payout_machinery.sql',
    state: 'applied',
    hasPreflight: false,
  },
  {
    number: '153',
    file: '153_ai_usage.sql',
    state: 'applied',
    hasPreflight: false,
  },
  {
    number: '154',
    file: '154_reviews_wishlist.sql',
    state: 'applied',
    hasPreflight: false,
  },
  {
    number: '155',
    file: '155_shipment_tracking.sql',
    state: 'applied',
    hasPreflight: false,
  },
  {
    number: '156',
    file: '156_analytics_indexes.sql',
    state: 'applied',
    hasPreflight: false,
  },
  {
    number: '157',
    file: '157_audit_ip_retention.sql',
    state: 'applied',
    hasPreflight: false,
  },
  {
    number: '158',
    file: '158_revoke_anon_public_on_new_functions.sql',
    state: 'applied',
    hasPreflight: false,
  },
  {
    number: '159',
    file: '159_pin_search_path_and_revoke_enqueue.sql',
    state: 'applied',
    hasPreflight: false,
  },
  {
    number: '160',
    file: '160_fk_indexes.sql',
    state: 'applied',
    hasPreflight: false,
  },
  {
    number: '161',
    file: '161_enable_pg_cron_pg_net.sql',
    state: 'applied',
    hasPreflight: false,
  },
  {
    number: '162',
    file: '162_cron_schedule.sql',
    state: 'pending',
    hasPreflight: true,
  },
  {
    number: '163',
    file: '163_orders_indexes.sql',
    state: 'applied',
    hasPreflight: false,
  },
  {
    number: '165',
    file: '165_revoke_anon_helpers.sql',
    state: 'cancelled',
    hasPreflight: true,
  },
  {
    number: '166',
    file: '166_voucher_transition_guard.sql',
    state: 'applied',
    hasPreflight: true,
  },
  {
    number: '167',
    file: '167_order_items_money_constraints.sql',
    state: 'applied',
    hasPreflight: true,
  },
  {
    number: '168',
    file: '168_wallet_ledger_client_readonly.sql',
    state: 'applied',
    hasPreflight: true,
  },
  {
    number: '169',
    file: '169_analytics_server_event_names.sql',
    state: 'pending',
    hasPreflight: true,
  },
  {
    number: '170',
    file: '170_composite_indexes_top_queries.sql',
    state: 'pending',
    hasPreflight: true,
  },
  {
    number: '171',
    file: '171_category_name_shekel_order.sql',
    state: 'pending',
    hasPreflight: true,
  },
  {
    number: '172',
    file: '172_hide_master_product_test_row.sql',
    state: 'pending',
    hasPreflight: true,
  },
  {
    number: '173',
    file: '173_products_retired_commission_percent.sql',
    state: 'pending',
    hasPreflight: true,
  },
  {
    number: '174',
    file: '174_wallet_topups.sql',
    state: 'pending',
    hasPreflight: true,
  },
  {
    number: '175',
    file: '175_referral_program_settings.sql',
    state: 'pending',
    hasPreflight: true,
  },
  {
    number: '176',
    file: '176_supplier_pin_rate_limit_per_staff.sql',
    state: 'pending',
    hasPreflight: true,
  },
  {
    number: '177',
    file: '177_set_updated_at_search_path.sql',
    state: 'pending',
    hasPreflight: true,
  },
] as const
