-- 192_seed_seo_redirects.sql
--
-- Seed public.seo_redirects with the legacy WordPress map.
--
-- GENERATED by scripts/build-legacy-redirects.mjs on 2026-09-09T05:34:49.146Z. Do not edit by
-- hand: `node scripts/build-legacy-redirects.mjs --check` fails if you do.
--
-- WHAT THIS FIXES
--
-- The table is EMPTY in production, measured 2026-09-09: 0 rows, so
-- every retired WordPress URL 404s today. The 301 machinery around it -- the
-- proxy lookup, the five-minute cache, the RLS policy, the hit counter -- was
-- built, reviewed and never given a single row to serve.
--
-- WHY NOT wp_import.fn_project_redirects
--
-- Because that function would write 34 rows and 13 of them are wrong against
-- production today: 11 categories pointing at Hebrew slugs that no longer
-- exist, a 410 on the live /blog route, and two 301s between live duplicate
-- products. The header of the generator script has the measurement.
--
-- DATA ONLY. No DDL. Re-running it is a no-op on unchanged rows.

BEGIN;

CREATE TEMP TABLE _seed (
  source_path  text PRIMARY KEY,
  target_path  text NOT NULL,
  status_code  smallint NOT NULL,
  entity_type  text,
  wp_id        bigint,
  mapping_rule text
) ON COMMIT DROP;

INSERT INTO _seed (source_path, target_path, status_code, entity_type, wp_id, mapping_rule) VALUES
  ('/affiliate-area', '', 410, 'page', 8990, 'page_gone_410'),
  ('/compare', '', 410, 'page', 2917, 'page_gone_410'),
  ('/coupon-scanner', '/scan', 301, 'page', 8842, 'page_redirect'),
  ('/dashboard', '', 410, 'page', 5865, 'page_gone_410'),
  ('/error-payment-payplus', '', 410, 'page', 7659, 'page_gone_410'),
  ('/my-account', '/account', 301, 'page', 3854, 'page_redirect'),
  ('/my-orders', '/account/orders', 301, 'page', 5867, 'page_redirect'),
  ('/my-wishlist', '', 410, 'page', 8966, 'page_gone_410'),
  ('/product-category/hot-deals', '/category/hot-deals', 301, 'category', 310, 'category_slug'),
  ('/product-category/uncategorized', '/products', 301, 'category', 15, 'category_slug'),
  ('/product-category/בעלי-מקצוע', '/category/professionals', 301, 'category', 276, 'category_slug'),
  ('/product-category/טלפונים-מחשבים-ואביזרים', '/category/phones-computers', 301, 'category', 272, 'category_slug'),
  ('/product-category/יופי-בריאות-וטיפוח', '/category/beauty-health', 301, 'category', 271, 'category_slug'),
  ('/product-category/מסעדות-ובתי-קפה', '/category/restaurants-cafes', 301, 'category', 270, 'category_slug'),
  ('/product-category/עד-99', '/category/under-99', 301, 'category', 311, 'category_slug'),
  ('/product-category/ציוד-ומזון-לבעלי-חיים', '/category/pets', 301, 'category', 275, 'category_slug'),
  ('/product-category/צימרים-מלונות-ונופש', '/category/vacation', 301, 'category', 274, 'category_slug'),
  ('/product-category/קורסים-express', '/category/courses', 301, 'category', 277, 'category_slug'),
  ('/product-category/תינוקות-וילדים', '/category/baby-kids', 301, 'category', 273, 'category_slug'),
  ('/product/7388', '/product/קוסמטיקאית', 301, 'product', 7388, 'wp_old_slug'),
  ('/product/product-template', '', 410, 'product', 6503, 'excluded_status:private'),
  ('/product/reverse-withdrawal-payment', '', 410, 'product', 8548, 'excluded_plugin_product'),
  ('/product/חופשה-חלומית-באחוזת-דניאל-3-לילות-copy', '', 410, 'product', 8481, 'excluded_status:private'),
  ('/recently-viewed', '', 410, 'page', 2174, 'page_gone_410'),
  ('/shop', '/products', 301, 'page', 3853, 'page_redirect'),
  ('/store-directory', '/products', 301, 'page', 2844, 'page_redirect'),
  ('/store-listing', '', 410, 'page', 5866, 'page_gone_410'),
  ('/track-your-order', '/account/orders', 301, 'page', 2181, 'page_redirect'),
  ('/wishlist', '', 410, 'page', 3855, 'page_gone_410'),
  ('/wishlist-archive', '', 410, 'page', 8965, 'page_gone_410'),
  ('/yith-compare', '', 410, 'page', 9246, 'page_gone_410'),
  ('/דף-בית-טסט', '/', 301, 'page', 6655, 'page_redirect'),
  ('/קניון-אקספרס-דף-הבית-מסדרים-לך-בילוי', '/', 301, 'page', 4878, 'page_redirect');

INSERT INTO public.seo_redirects
  (source_path, target_path, status_code, entity_type, wp_id, mapping_rule, is_active)
SELECT source_path, target_path, status_code, entity_type, wp_id, mapping_rule, true
FROM _seed
ON CONFLICT (source_path) DO UPDATE
  SET target_path  = EXCLUDED.target_path,
      status_code  = EXCLUDED.status_code,
      entity_type  = EXCLUDED.entity_type,
      wp_id        = EXCLUDED.wp_id,
      mapping_rule = EXCLUDED.mapping_rule,
      is_active    = true,
      updated_at   = now();

-- Rows this file does NOT carry are DEACTIVATED, not deleted.
--
-- Deleting would throw away the hit counter, which is the only evidence of
-- whether a retired URL still gets traffic; `is_active = false` stops it being
-- served while keeping the count. The proxy filters on is_active.
UPDATE public.seo_redirects r
   SET is_active = false, updated_at = now()
 WHERE r.is_active
   AND NOT EXISTS (SELECT 1 FROM _seed s WHERE s.source_path = r.source_path);

DO $$
DECLARE n int;
BEGIN
  SELECT count(*) INTO n FROM public.seo_redirects WHERE is_active;
  IF n <> 33 THEN
    RAISE EXCEPTION 'expected 33 active redirects, found %', n;
  END IF;
END $$;

COMMIT;
